<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SparepartManagementSystem.Domain\SparepartManagementSystem.Domain.csproj"/>
        <ProjectReference Include="..\SparepartManagementSystem.Shared\SparepartManagementSystem.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.35" />
        <PackageReference Include="Dapper.SqlBuilder" Version="2.0.78"/>
        <PackageReference Include="MySqlConnector" Version="2.3.7" />
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
        <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    </ItemGroup>

</Project>
