<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>b482acea-dd83-421a-9cf2-051299c5927e</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SparepartManagementSystem.Domain\SparepartManagementSystem.Domain.csproj" />
    </ItemGroup>

<ItemGroup>
      <PackageReference Include="Dapper.SqlBuilder" Version="2.0.78" />
      <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.0" />
    </ItemGroup>

</Project>
